version: '3.0'
services:
    redis-m1:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./configs/m1-redis.conf:/etc/redis/redis.conf
        image: "redis-sentinel"
        command: redis-server /etc/redis/redis.conf
        networks:
            app_net:
                ipv4_address: 172.48.0.10
        container_name: redis-m1
    redis-r1:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./configs/r-redis.conf:/etc/redis/redis.conf
        image: "redis-sentinel"
        depends_on:
            - "redis-m1"
        command: redis-server /etc/redis/redis.conf
        networks:
            app_net:
                ipv4_address: 172.48.0.11
        container_name: redis-r1
    redis-r2:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./configs/r-redis.conf:/etc/redis/redis.conf
        image: "redis-sentinel"
        depends_on:
            - "redis-m1"
        command: redis-server /etc/redis/redis.conf
        networks:
            app_net:
                ipv4_address: 172.48.0.12
        container_name: redis-r2
    sentinel-1:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        image: "redis-sentinel"
        depends_on:
            - "redis-m1"
            - "redis-r2"
        command: redis-server /etc/redis/sentinel.conf --sentinel
        networks:
            app_net:
                ipv4_address: 172.48.0.13
        container_name: s-1
    sentinel-2:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        image: "redis-sentinel"
        depends_on:
            - "redis-m1"
            - "redis-r2"
        command: redis-server /etc/redis/sentinel.conf --sentinel
        networks:
            app_net:
                ipv4_address: 172.48.0.14
        container_name: s-2
    sentinel-3:
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        image: "redis-sentinel"
        depends_on:
            - "redis-m1"
            - "redis-r2"
        command: redis-server /etc/redis/sentinel.conf --sentinel
        networks:
            app_net:
                ipv4_address: 172.48.0.15
        container_name: s-3

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.48.0.0/24
