version: '1.0'
services:
    db:
        build:
            context: ./debian-percona
            dockerfile: Dockerfile
        volumes:
            - ./db_data:/var/lib/mysql
        restart: always
        image: "debian-percona:5.7"
        networks:
            app_net:
                ipv4_address: 172.24.0.8
        container_name: pb-db

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -
              subnet: 172.24.0.0/24
